export { ExcelComTool } from "./excel-com"
export { WordComTool } from "./word-com"
export { PptComTool } from "./ppt-com"
export { ExcelReadTool } from "./excel-read"
export { WordReadTool } from "./word-read"
export { PptReadTool } from "./ppt-read"
export * from "./docmap"