export { ExcelComTool } from "./tools/excel-com"
export { WordComTool } from "./tools/word-com"
export { PptComTool } from "./tools/ppt-com"
export { ExcelReadTool } from "./tools/excel-read"
export { WordReadTool } from "./tools/word-read"
export { PptReadTool } from "./tools/ppt-read"
export * from "./docmap"