import { Injectable, Logger, Optional, Inject } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import mammoth from 'mammoth';
import * as XLSX from 'xlsx';
import { ToolResult } from '../interfaces/tool-result.interface.js';
import { PdfReportBuilder } from './generators/pdf-report-builder.js';
import { DocxReportBuilder } from './generators/docx-report-builder.js';
import { ExcelReportBuilder } from './generators/excel-report-builder.js';
import { WordComService } from '../../interaction/word-com.service.js';
import { ExcelComService } from '../../interaction/excel-com.service.js';
import { PptComService } from '../../interaction/ppt-com.service.js';

@Injectable()
export class DocumentConverterTool {
  private readonly logger = new Logger(DocumentConverterTool.name);
  private readonly pdfBuilder = new PdfReportBuilder();
  private readonly docxBuilder = new DocxReportBuilder();
  private readonly excelBuilder = new ExcelReportBuilder();

  constructor(
    @Optional() @Inject(WordComService) private readonly wordCom?: WordComService,
    @Optional() @Inject(ExcelComService) private readonly excelCom?: ExcelComService,
    @Optional() @Inject(PptComService) private readonly pptCom?: PptComService,
  ) {}

  async convertDocument(options: {
    sourcePath: string;
    targetFormat: 'pdf' | 'docx' | 'xlsx' | 'csv' | 'txt';
    outputPath?: string;
  }): Promise<ToolResult> {
    const startTime = Date.now();
    const { sourcePath, targetFormat } = options;

    if (!sourcePath || !fs.existsSync(sourcePath)) {
      return {
        status: 'error',
        data: {},
        preview: `Source file not found: ${sourcePath}`,
        metadata: {
          toolName: 'convert_document',
          displayName: 'Convert Document',
          executionTime: Date.now() - startTime,
        },
        error: {
          code: 'FILE_NOT_FOUND',
          message: `Source file not found at ${sourcePath}`,
        },
      };
    }

    const sourceExt = path.extname(sourcePath).toLowerCase().replace('.', '');
    const sourceBase = path.basename(sourcePath, path.extname(sourcePath));
    const targetPath =
      options.outputPath ||
      path.join(path.dirname(sourcePath), `${sourceBase}.${targetFormat}`);

    try {
      // 1. DOCX -> PDF (Prioritize Native Word COM for 100% font/layout fidelity)
      if (sourceExt === 'docx' && targetFormat === 'pdf') {
        if (this.wordCom?.isAvailable) {
          try {
            await this.wordCom.editWord(sourcePath, [
              { action: 'export_pdf', exportPdfPath: targetPath },
            ]);
            if (fs.existsSync(targetPath)) {
              return {
                status: 'success',
                data: {
                  sourcePath,
                  targetPath,
                  sourceFormat: sourceExt,
                  targetFormat,
                  engine: 'Microsoft Word Native COM Engine',
                  size: fs.statSync(targetPath).size,
                },
                preview: `Successfully converted ${path.basename(sourcePath)} to PDF via Native Microsoft Word Engine (${path.basename(targetPath)})`,
                metadata: {
                  toolName: 'convert_document',
                  displayName: 'Convert Document',
                  executionTime: Date.now() - startTime,
                  filename: path.basename(targetPath),
                },
              };
            }
          } catch (comErr: any) {
            this.logger.warn(`Native Word COM export failed (${comErr.message}), falling back to HTML/Chromium`);
          }
        }

        const htmlResult = await mammoth.convertToHtml({ path: sourcePath });
        const rawHtml = htmlResult.value || '';
        const title = sourceBase.replace(/[-_]/g, ' ');

        const styledHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  @page {
    size: A4;
    margin: 20mm 15mm 20mm 15mm;
  }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1e293b;
    line-height: 1.6;
    font-size: 13px;
    padding: 0;
    margin: 0;
  }
  h1 { font-size: 22px; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 0; }
  h2 { font-size: 17px; color: #1e293b; margin-top: 20px; }
  h3 { font-size: 14px; color: #334155; }
  p { margin: 8px 0; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 12px; }
  th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
  th { background-color: #f1f5f9; font-weight: 600; color: #0f172a; }
  tr:nth-child(even) { background-color: #f8fafc; }
  ul, ol { padding-left: 20px; margin: 8px 0; }
  li { margin: 4px 0; }
  .footer { margin-top: 30px; font-size: 10px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
  ${rawHtml}
  <div class="footer">Generated by Arunaki Document Engine</div>
</body>
</html>`;

        let convertedViaChromium = false;
        try {
          const { chromium } = await import('playwright');
          const browser = await chromium.launch({ headless: true });
          const page = await browser.newPage();
          await page.setContent(styledHtml, { waitUntil: 'load' });
          await page.pdf({
            path: targetPath,
            format: 'A4',
            printBackground: true,
            margin: {
              top: '20mm',
              right: '15mm',
              bottom: '20mm',
              left: '15mm',
            },
          });
          await browser.close();
          convertedViaChromium = true;
          this.logger.log(
            `Rendered DOCX -> PDF via Chromium Engine: ${targetPath}`,
          );
        } catch (chromiumErr: any) {
          this.logger.warn(
            `Chromium render unavailable (${chromiumErr.message}), falling back to vector PDF builder`,
          );
          const text =
            (await mammoth.extractRawText({ path: sourcePath })).value || '';
          await this.pdfBuilder.generatePdf(
            title,
            text,
            path.basename(targetPath),
            targetPath,
          );
        }

        return {
          status: 'success',
          data: {
            sourcePath,
            targetPath,
            sourceFormat: sourceExt,
            targetFormat,
            engine: convertedViaChromium
              ? 'Chromium (A4 CSS Print)'
              : 'PDF-Lib Vector',
            size: fs.existsSync(targetPath) ? fs.statSync(targetPath).size : 0,
          },
          preview: `Successfully converted ${path.basename(sourcePath)} to PDF (${path.basename(targetPath)})`,
          metadata: {
            toolName: 'convert_document',
            displayName: 'Convert Document',
            executionTime: Date.now() - startTime,
            filename: path.basename(targetPath),
          },
        };
      }

      // 2. TXT / MD -> PDF
      if (
        (sourceExt === 'txt' || sourceExt === 'md') &&
        targetFormat === 'pdf'
      ) {
        const text = fs.readFileSync(sourcePath, 'utf-8');
        const title = sourceBase.replace(/[-_]/g, ' ');
        await this.pdfBuilder.generatePdf(
          title,
          text,
          path.basename(targetPath),
          targetPath,
        );
        return {
          status: 'success',
          data: {
            sourcePath,
            targetPath,
            sourceFormat: sourceExt,
            targetFormat,
          },
          preview: `Successfully converted ${path.basename(sourcePath)} to PDF (${path.basename(targetPath)})`,
          metadata: {
            toolName: 'convert_document',
            displayName: 'Convert Document',
            executionTime: Date.now() - startTime,
          },
        };
      }

      // 3. TXT / MD -> DOCX
      if (
        (sourceExt === 'txt' || sourceExt === 'md') &&
        targetFormat === 'docx'
      ) {
        const text = fs.readFileSync(sourcePath, 'utf-8');
        const title = sourceBase.replace(/[-_]/g, ' ');
        await this.docxBuilder.generateDocx(
          title,
          text,
          path.basename(targetPath),
          targetPath,
        );
        return {
          status: 'success',
          data: {
            sourcePath,
            targetPath,
            sourceFormat: sourceExt,
            targetFormat,
          },
          preview: `Successfully converted ${path.basename(sourcePath)} to DOCX (${path.basename(targetPath)})`,
          metadata: {
            toolName: 'convert_document',
            displayName: 'Convert Document',
            executionTime: Date.now() - startTime,
          },
        };
      }

      // 4. XLSX -> CSV
      if (
        (sourceExt === 'xlsx' || sourceExt === 'xls') &&
        targetFormat === 'csv'
      ) {
        const wb = XLSX.readFile(sourcePath);
        const firstSheet = wb.Sheets[wb.SheetNames[0]];
        const csvContent = XLSX.utils.sheet_to_csv(firstSheet);
        fs.writeFileSync(targetPath, csvContent, 'utf-8');
        return {
          status: 'success',
          data: {
            sourcePath,
            targetPath,
            sourceFormat: sourceExt,
            targetFormat,
          },
          preview: `Successfully converted ${path.basename(sourcePath)} to CSV (${path.basename(targetPath)})`,
          metadata: {
            toolName: 'convert_document',
            displayName: 'Convert Document',
            executionTime: Date.now() - startTime,
          },
        };
      }

      // 5. XLSX -> PDF (Prioritize Native Excel COM)
      if (
        (sourceExt === 'xlsx' || sourceExt === 'xls') &&
        targetFormat === 'pdf'
      ) {
        if (this.excelCom?.isAvailable) {
          try {
            await this.excelCom.editExcel(sourcePath, [
              { action: 'export_pdf', range: targetPath },
            ]);
            if (fs.existsSync(targetPath)) {
              return {
                status: 'success',
                data: {
                  sourcePath,
                  targetPath,
                  sourceFormat: sourceExt,
                  targetFormat,
                  engine: 'Microsoft Excel Native COM Engine',
                  size: fs.statSync(targetPath).size,
                },
                preview: `Successfully converted ${path.basename(sourcePath)} to PDF via Native Microsoft Excel Engine (${path.basename(targetPath)})`,
                metadata: {
                  toolName: 'convert_document',
                  displayName: 'Convert Document',
                  executionTime: Date.now() - startTime,
                  filename: path.basename(targetPath),
                },
              };
            }
          } catch (comErr: any) {
            this.logger.warn(`Native Excel COM export failed (${comErr.message}), falling back to table renderer`);
          }
        }

        const wb = XLSX.readFile(sourcePath);
        const firstSheet = wb.Sheets[wb.SheetNames[0]];
        const rows = XLSX.utils.sheet_to_json(firstSheet, {
          header: 1,
        });
        const formattedLines = rows
          .map((r) => (Array.isArray(r) ? r.join(' | ') : String(r)))
          .join('\n');
        const title = `${sourceBase} Spreadsheet Report`;
        await this.pdfBuilder.generatePdf(
          title,
          formattedLines,
          path.basename(targetPath),
          targetPath,
        );
        return {
          status: 'success',
          data: {
            sourcePath,
            targetPath,
            sourceFormat: sourceExt,
            targetFormat,
          },
          preview: `Successfully converted ${path.basename(sourcePath)} to PDF (${path.basename(targetPath)})`,
          metadata: {
            toolName: 'convert_document',
            displayName: 'Convert Document',
            executionTime: Date.now() - startTime,
          },
        };
      }

      // 6. PPTX -> PDF (Prioritize Native PowerPoint COM)
      if (
        (sourceExt === 'pptx' || sourceExt === 'ppt') &&
        targetFormat === 'pdf'
      ) {
        if (this.pptCom?.isAvailable) {
          try {
            await this.pptCom.editPpt(sourcePath, [
              { action: 'export_pdf', exportPdfPath: targetPath },
            ]);
            if (fs.existsSync(targetPath)) {
              return {
                status: 'success',
                data: {
                  sourcePath,
                  targetPath,
                  sourceFormat: sourceExt,
                  targetFormat,
                  engine: 'Microsoft PowerPoint Native COM Engine',
                  size: fs.statSync(targetPath).size,
                },
                preview: `Successfully converted ${path.basename(sourcePath)} to PDF via Native Microsoft PowerPoint Engine (${path.basename(targetPath)})`,
                metadata: {
                  toolName: 'convert_document',
                  displayName: 'Convert Document',
                  executionTime: Date.now() - startTime,
                  filename: path.basename(targetPath),
                },
              };
            }
          } catch (comErr: any) {
            this.logger.warn(`Native PPT COM export failed (${comErr.message})`);
          }
        }
      }

      // 7. Fallback / Unsupported pair
      return {
        status: 'error',
        data: {},
        preview: `Conversion from ${sourceExt} to ${targetFormat} is not currently supported.`,
        metadata: {
          toolName: 'convert_document',
          displayName: 'Convert Document',
          executionTime: Date.now() - startTime,
        },
        error: {
          code: 'UNSUPPORTED_CONVERSION',
          message: `Cannot convert ${sourceExt} to ${targetFormat}`,
        },
      };
    } catch (err: any) {
      this.logger.error(`Error converting document: ${err.message}`, err.stack);
      return {
        status: 'error',
        data: {},
        preview: `Conversion failed: ${err.message}`,
        metadata: {
          toolName: 'convert_document',
          displayName: 'Convert Document',
          executionTime: Date.now() - startTime,
        },
        error: { code: 'CONVERSION_FAILED', message: err.message },
      };
    }
  }
}
